site_name: Notas Musicais
repo_url: https://github.com/cleytongomes/notas-musicais
repo_name: cleytongomesx/notas-musicais
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  -  attr_list

watch:
  -  notas_musicais

extra_css:
  -  stylesheets/extra.css

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [notas_musicais]